### ISSUE TITLE
表头如何固定

### ISSUE THREAD

**Issue by dujingli** [superZhouDaLu/BlogExample#4]
用原生指令height或者maxHeight 设置了高度后，表头是固定的，在实现过程中，发现按您的这样设置，无法固定表头，请问这个问题需要怎么解决呢

**Comment by superZhouDaLu** [comment]
我看了下项目表头可以固定，是否缺少了某个属性？

**Comment by dujingli** [comment]
我看您的App.vue文件中的table设置了height='100px'，编写v-adaptive这个指令的目的不就是为了动态的设置表格高度么，那为什么还要在表格里设置height="100px"呢，我的表格是没有这个height指令的，所以无法固定表头

**Comment by dujingli** [comment]
加了height=100px 确实可以固定表头了，但我不是很理解，我觉得编写v-adaptive的指令，就是重写height或者maxheight指令来根据浏览器高度动态设置表格的高度，但却无法固定表头，必须要在el-table中再添加height属性才行，这是为什么呢？
